// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu9MyRIey0hxBwwa-9z3gWr2xQCcZoYP0',
    appId: '1:474887112022:web:7cf0a8bcb4e3e4dbabc2f7',
    messagingSenderId: '474887112022',
    projectId: 'emart-a39ed',
    authDomain: 'emart-a39ed.firebaseapp.com',
    storageBucket: 'emart-a39ed.appspot.com',
    measurementId: 'G-66X17S79CZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbHuUagrVjZT1uXszP7Vf3L7eBqPIA9-w',
    appId: '1:474887112022:android:22f1960e7a79ff61abc2f7',
    messagingSenderId: '474887112022',
    projectId: 'emart-a39ed',
    storageBucket: 'emart-a39ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbau7JwYZ2wJVyNB5QnxozNxAaO4Yvgho',
    appId: '1:474887112022:ios:fb706c81e6f9a8bbabc2f7',
    messagingSenderId: '474887112022',
    projectId: 'emart-a39ed',
    storageBucket: 'emart-a39ed.appspot.com',
    iosClientId: '474887112022-kdfu8lg81cao9or4417i7rpt221fkode.apps.googleusercontent.com',
    iosBundleId: 'com.example.kiddyMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbau7JwYZ2wJVyNB5QnxozNxAaO4Yvgho',
    appId: '1:474887112022:ios:fb706c81e6f9a8bbabc2f7',
    messagingSenderId: '474887112022',
    projectId: 'emart-a39ed',
    storageBucket: 'emart-a39ed.appspot.com',
    iosClientId: '474887112022-kdfu8lg81cao9or4417i7rpt221fkode.apps.googleusercontent.com',
    iosBundleId: 'com.example.kiddyMarket',
  );
}
